### PR TITLE
Switching to tensorflow keras API for Tensorflow 2.0+

### PR DESCRIPTION
**Pull request by Blubbaa**
Probably needs some review and more testing.

### CODE REVIEW

**Comment by JesperDramsch** [comment]
This is amazing. Thank you for putting in the work.

As you mentioned in the comment chain, we should do some thorough review and testing on this, as the unittests don't cover much of the code base at this point. But I'm really happy you initiated this step!

**Comment by hosseybposh** [comment]
hey guys, first I wanna thank to Jasper for the amazing repo, and thanks Blubbaa for initiating this.
I was wondering what the status is on this? I'd be happy to help out if needed

**Comment by Blubbaa** [comment]
Looks like not much happened in the mean time. Maybe someone can write some more unit-tests and verify the code base. And then Jesper can accept the pull request?

**Comment by JesperDramsch** [comment]
Oh sorry, I was treating this as a WIP pull request. I am reluctant to merge anything before we have a proper test suite.

I have been harassed heavily by someone that couldn't get the original version to work and would like to avoid that by introducing possible breaking changes.

**Comment by Blubbaa** [comment]
Yes, that's understandable and I also guessed this is the reason why it is not yet merged. From my side the pull request was finshed, but as I said this needs _at least_ someone else to look over the changes and test it. Unfortunately I currently don't have the time to write more unittests etc.

**Comment by JesperDramsch** [comment]
Is it okay for you to keep it open for now until either you, I, or another volunteer like @hosseybposh finds time and energy to work on this?

If I can dream a bit, if we can get this tested and to TF2, we should try and get it published in JOSS or something.

**Comment by JesperDramsch** [comment]
Thank you @Blubbaa. #20 expanded on your work, so I merged both and updated the PyPI package.

Appreciate it!

**Pull request merged**
